CREATE TABLE USERS(
  USER_ID VARCHAR2(50) PRIMARY KEY,
  USER_PASSWORD VARCHAR2(50) NOT NULL,
  USER_NAME VARCHAR2(50) NOT NULL,
  USER_NICKNAME VARCHAR2(50) UNIQUE NOT NULL,
  BIRTH_DATE DATE NOT NULL,
  USER_EMAIL VARCHAR2(50) UNIQUE NOT NULL,
  USER_PHONE VARCHAR2(50) UNIQUE NOT NULL,
  LICENSE VARCHAR2(50) UNIQUE NOT NULL,
  USER_REG_DATE DATE DEFAULT SYSDATE,
  USER_UPDATE DATE DEFAULT SYSDATE,
  ENABLED CHAR(1) DEFAULT '1'
);

CREATE TABLE AUTHORITIES(
  USER_ID VARCHAR2(50) NOT NULL,
  AUTHORITY VARCHAR2(50) NOT NULL,
  CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE UNIQUE INDEX IX_AUTH_USER_ID ON AUTHORITIES (USER_ID, AUTHORITY);