/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-10-08 12:25:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Equipo - Free Bootstrap 4 Template by Colorlib</title>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0//resources/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/jquery.timepicker.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/flaticon.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"py-3\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row d-flex align-items-start align-items-center px-3 px-md-0\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 d-flex mb-2 mb-md-0\">\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand d-flex align-items-center\" href=\"index.html\"><span class=\"flaticon flaticon-road-roller\"></span><span>Equipo <small>Rental Heavy Equipment</small></span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 d-flex topper mb-md-0 mb-2 align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-map\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"pr-md-4 pl-md-3 pl-3 text\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"con\"><span>Free Call</span> <span>+1 234 456 78910</span></p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"con\">Call Us Now 24/7 Customer Support</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 d-flex topper mb-md-0 align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"icon d-flex justify-content-center align-items-center\"><span class=\"fa fa-paper-plane\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text pl-3 pl-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"hr\"><span>Our Location</span></p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"con\">198 West 21th Street, Suite 721 New York NY 10016</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("\t\t<div class=\"container d-flex align-items-center\">\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"fa fa-bars\"></span> Menu\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav m-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a href=\"index.html\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"about.html\" class=\"nav-link\">About</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"services.html\" class=\"nav-link\">Rental Services</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"gallery.html\" class=\"nav-link\">Gallery</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"blog.html\" class=\"nav-link\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"contact.html\" class=\"nav-link\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item cta\"><a href=\"contact.html\" class=\"nav-link\">Request A Quote</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- END nav -->\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"hero-wrap js-fullheight\" style=\"background-image: url('/resources/images/bg_2.jpg');\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row no-gutters slider-text js-fullheight align-items-center justify-content-center\" data-scrollax-parent=\"true\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-9 ftco-animate text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"mb-4\">Lease The Right Equipment For Your Job</h1>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove.</p>\r\n");
      out.write("\t\t\t\t\t\t<p><a href=\"#\" class=\"btn btn-primary\">Contact us</a> <a href=\"#\" class=\"btn btn-white\">Request A Quote</a></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section ftco-no-pt ftco-no-pb ftco-services-2 bg-primary\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row d-flex\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-7 py-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"py-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row justify-content-center pb-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 heading-section ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"mb-3\">Why Choose To Rent In Equipo</h2>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media block-6 services d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"icon justify-content-center align-items-center d-flex\"><span class=\"flaticon-customer-service\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"media-body pl-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"heading mb-3\">24/7 Customer Service</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>      \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media block-6 services d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"icon justify-content-center align-items-center d-flex\"><span class=\"flaticon-road-roller\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"media-body pl-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"heading mb-3\">Prompt Delivery</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>      \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media block-6 services d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"icon justify-content-center align-items-center d-flex\"><span class=\"flaticon-road-roller\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"media-body pl-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"heading mb-3\">Reliable Equipment</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>      \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media block-6 services d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"icon justify-content-center align-items-center d-flex\"><span class=\"flaticon-road-roller\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"media-body pl-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"heading mb-3\">New Heavy Equipment</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>      \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-5 d-flex\">\r\n");
      out.write("\t\t\t\t\t<div class=\"appointment-wrap p-4 p-lg-5 d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" class=\"appointment-form ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Request Quote</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"First Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Last Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Phone\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-field\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"select-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"icon\"><span class=\"fa fa-chevron-down\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Your Services</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Forklift</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Bulldozer</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Excavator</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Road Roller</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Other Services</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea name=\"\" id=\"\" cols=\"30\" rows=\"4\" class=\"form-control\" placeholder=\"Message\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Appointment\" class=\"btn btn-primary py-3 px-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section ftco-counter ftco-no-pt ftco-no-pb\" id=\"about-section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 d-flex align-items-stretch\">\r\n");
      out.write("\t\t\t\t\t<div class=\"about-wrap img w-100\" style=\"background-image: url(/resources/images/about.jpg);\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 py-5 pl-md-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row justify-content-center mb-4 pt-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 heading-section ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"subheading\">Welcome to Equipo</span>\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"mb-4\">Welcome to Equipo A Rental Heavy Equipment</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-18\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"number\" data-number=\"50\">0</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Years of Experienced</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-18\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"number\" data-number=\"4500\">0</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Customers Served</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-18\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"number\" data-number=\"300\">0</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Number of Equipment</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-18\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"number\" data-number=\"300\">0</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Number of Staffs</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-intro img\" style=\"background-image: url(/resources/images/bg_3.jpg);\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 text-center\">\r\n");
      out.write("\t\t\t\t\t<h2>We Are Equipo A Heavy Equipment Renting Company</h2>\r\n");
      out.write("\t\t\t\t\t<p>We can manage your dream building A small river named Duden flows by their place</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"mb-0\"><a href=\"#\" class=\"btn btn-primary px-4 py-3\">Make An Appointment</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section\">\r\n");
      out.write("\t\t<div class=\"container-fluid px-md-4\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center mb-5 pb-2\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 text-center heading-section ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<span class=\"subheading\">Services</span>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"mb-4\">Rental Services</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"services-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img\" style=\"background-image: url(/resources/images/services-1.jpg);\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Bulldozer</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"services-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img\" style=\"background-image: url(/resources/images/services-2.jpg);\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Forklift</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"services-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img\" style=\"background-image: url(/resources/images/services-3.jpg);\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Crane</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"services-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img\" style=\"background-image: url(/resources/images/services-4.jpg);\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Excavator</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section testimony-section img\" style=\"background-image: url(/resources/images/bg_1.jpg);\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-7 text-center heading-section heading-section-white ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<span class=\"subheading\">Read Testimonials</span>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"mb-4\">Our Happy Customer Says</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row ftco-animate justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-testimony owl-carousel ftco-owl\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\" style=\"background-image: url(/resources/images/person_1.jpg)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\" style=\"background-image: url(/resources/images/person_2.jpg)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\" style=\"background-image: url(/resources/images/person_3.jpg)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\" style=\"background-image: url(/resources/images/person_1.jpg)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\" style=\"background-image: url(/resources/images/person_3.jpg)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section bg-light\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-10 heading-section text-center ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<span class=\"subheading\">Our Blog</span>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"mb-4\">Latest Blog Updates</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row d-flex\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<div class=\"blog-entry\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('/resources/images/image_1.jpg');\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text d-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-calendar mr-2\"></span>Aug. 27, 2020</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-user mr-2\"></span>Admin</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"meta-chat\"><span class=\"fa fa-comment mr-2\"></span> 3</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"heading\"><a href=\"#\">New Heavy Equipment To Launch</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia...</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p><a href=\"blog.html\" class=\"btn btn-secondary py-2 px-3\">Read more</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<div class=\"blog-entry\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('/resources/images/image_2.jpg');\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text d-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-calendar mr-2\"></span>Aug. 27, 2020</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-user mr-2\"></span>Admin</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"meta-chat\"><span class=\"fa fa-comment mr-2\"></span> 3</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"heading\"><a href=\"#\">New Heavy Equipment To Launch</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia...</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p><a href=\"blog.html\" class=\"btn btn-secondary py-2 px-3\">Read more</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<div class=\"blog-entry\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('/resources/images/image_3.jpg');\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text d-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-calendar mr-2\"></span>Aug. 27, 2020</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-user mr-2\"></span>Admin</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"meta-chat\"><span class=\"fa fa-comment mr-2\"></span> 3</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"heading\"><a href=\"#\">New Heavy Equipment To Launch</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia...</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p><a href=\"blog.html\" class=\"btn btn-secondary py-2 px-3\">Read more</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"ftco-footer\">\r\n");
      out.write("\t\t<div class=\"container mb-5 pb-4\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ftco-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"ftco-heading-2 logo d-flex align-items-center\"><a href=\"#\"><span class=\"flaticon-road-roller flaticon\"></span><span>Equipo</span></a></h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"ftco-footer-social list-unstyled mt-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ftco-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"ftco-heading-2\">Links</h2>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Rental Services</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ftco-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"ftco-heading-2\">Services</h2>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Customer Services</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Prompt Delivery</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Reliable Equipment</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>New Heavy Equipment</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ftco-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"block-23 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span class=\"fa fa-map-marker mr-3\"></span><span class=\"text\">203 Fake St. Mountain View, San Francisco, California, USA</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-phone mr-3\"></span><span class=\"text\">+2 392 3929 210</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-paper-plane mr-3\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container-fluid bg-primary py-5\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<p class=\"mb-0\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\t\tCopyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- loader -->\r\n");
      out.write("\t\t<div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/popper.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/google-map.js\"></script>\r\n");
      out.write("\t\t<script src=\"/resources/js/main.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</body>\r\n");
      out.write("\t</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
