/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-10-08 11:03:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<title>Equipo - Free Bootstrap 4 Template by Colorlib</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0//resources/css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/owl.theme.default.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/bootstrap-datepicker.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/jquery.timepicker.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/flaticon.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"py-3\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div\n");
      out.write("\t\t\t\tclass=\"row d-flex align-items-start align-items-center px-3 px-md-0\">\n");
      out.write("\t\t\t\t<div class=\"col-md-4 d-flex mb-2 mb-md-0\">\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand d-flex align-items-center\" href=\"index.html\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"flaticon flaticon-road-roller\"></span><span>Equipo <small>Rental\n");
      out.write("\t\t\t\t\t\t\t\tHeavy Equipment</small></span></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4 d-flex topper mb-md-0 mb-2 align-items-center\">\n");
      out.write("\t\t\t\t\t<div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-map\"></span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"pr-md-4 pl-md-3 pl-3 text\">\n");
      out.write("\t\t\t\t\t\t<p class=\"con\">\n");
      out.write("\t\t\t\t\t\t\t<span>Free Call</span> <span>+1 234 456 78910</span>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"con\">Call Us Now 24/7 Customer Support</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4 d-flex topper mb-md-0 align-items-center\">\n");
      out.write("\t\t\t\t\t<div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-paper-plane\"></span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"text pl-3 pl-md-3\">\n");
      out.write("\t\t\t\t\t\t<p class=\"hr\">\n");
      out.write("\t\t\t\t\t\t\t<span>Our Location</span>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"con\">198 West 21th Street, Suite 721 New York NY\n");
      out.write("\t\t\t\t\t\t\t10016</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<nav\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light\"\n");
      out.write("\t\tid=\"ftco-navbar\">\n");
      out.write("\t\t<div class=\"container d-flex align-items-center\">\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\tdata-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\n");
      out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t<span class=\"fa fa-bars\"></span> Menu\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav m-auto\">\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a href=\"index.html\"\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"about.html\" class=\"nav-link\">About</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"services.html\" class=\"nav-link\">Rental\n");
      out.write("\t\t\t\t\t\t\tServices</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"gallery.html\" class=\"nav-link\">Gallery</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"blog.html\" class=\"nav-link\">Blog</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"contact.html\" class=\"nav-link\">Contact</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item cta\"><a href=\"contact.html\"\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link\">Request A Quote</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\t<!-- END nav -->\n");
      out.write("\n");
      out.write("\t<section class=\"hero-wrap js-fullheight\"\n");
      out.write("\t\tstyle=\"background-image: url('/resources/images/bg_2.jpg');\"\n");
      out.write("\t\tdata-stellar-background-ratio=\"0.5\">\n");
      out.write("\t\t<div class=\"overlay\"></div>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div\n");
      out.write("\t\t\t\tclass=\"row no-gutters slider-text js-fullheight align-items-center justify-content-center\"\n");
      out.write("\t\t\t\tdata-scrollax-parent=\"true\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-9 ftco-animate text-center\">\n");
      out.write("\t\t\t\t\t<div class=\"mt-5\">\n");
      out.write("\t\t\t\t\t\t<h1 class=\"mb-4\">Lease The Right Equipment For Your Job</h1>\n");
      out.write("\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains, far\n");
      out.write("\t\t\t\t\t\t\tfrom the countries Vokalia and Consonantia, there live the blind\n");
      out.write("\t\t\t\t\t\t\ttexts. Separated they live in Bookmarksgrove.</p>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Contact us</a> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-white\">Request A Quote</a>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section\n");
      out.write("\t\tclass=\"ftco-section ftco-no-pt ftco-no-pb ftco-services-2 bg-primary\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row d-flex\">\n");
      out.write("\t\t\t\t<div class=\"col-md-7 py-5\">\n");
      out.write("\t\t\t\t\t<div class=\"py-lg-5\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row justify-content-center pb-5\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 heading-section ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"mb-3\">Why Choose To Rent In Equipo</h2>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media block-6 services d-flex\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon justify-content-center align-items-center d-flex\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"flaticon-customer-service\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"media-body pl-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"heading mb-3\">24/7 Customer Service</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsupplies it with the necessary regelialia.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media block-6 services d-flex\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon justify-content-center align-items-center d-flex\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"flaticon-road-roller\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"media-body pl-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"heading mb-3\">Prompt Delivery</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsupplies it with the necessary regelialia.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media block-6 services d-flex\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon justify-content-center align-items-center d-flex\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"flaticon-road-roller\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"media-body pl-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"heading mb-3\">Reliable Equipment</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsupplies it with the necessary regelialia.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media block-6 services d-flex\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon justify-content-center align-items-center d-flex\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"flaticon-road-roller\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"media-body pl-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"heading mb-3\">New Heavy Equipment</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>A small river named Duden flows by their place and\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsupplies it with the necessary regelialia.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-5 d-flex\">\n");
      out.write("\t\t\t\t\t<div class=\"appointment-wrap p-4 p-lg-5 d-flex align-items-center\">\n");
      out.write("\t\t\t\t\t\t<div class=\"overlay\"></div>\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" class=\"appointment-form ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t<h3>Request Quote</h3>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"First Name\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Last Name\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Phone\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-field\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"select-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"icon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-chevron-down\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"\" id=\"\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Your Services</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Forklift</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Bulldozer</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Excavator</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Road Roller</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Other Services</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea name=\"\" id=\"\" cols=\"30\" rows=\"4\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Message\"></textarea>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Appointment\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary py-3 px-4\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section class=\"ftco-section ftco-counter ftco-no-pt ftco-no-pb\"\n");
      out.write("\t\tid=\"about-section\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-6 d-flex align-items-stretch\">\n");
      out.write("\t\t\t\t\t<div class=\"about-wrap img w-100\"\n");
      out.write("\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/about.jpg);\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-6 py-5 pl-md-5\">\n");
      out.write("\t\t\t\t\t<div class=\"row justify-content-center mb-4 pt-md-4\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 heading-section ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"subheading\">Welcome to Equipo</span>\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"mb-4\">Welcome to Equipo A Rental Heavy Equipment</h2>\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\t\t\tcountries Vokalia and Consonantia, there live the blind texts.\n");
      out.write("\t\t\t\t\t\t\t\tSeparated they live in Bookmarksgrove right at the coast of the\n");
      out.write("\t\t\t\t\t\t\t\tSemantics, a large language ocean.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-md-6 d-flex justify-content-center counter-wrap ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-18\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"number\" data-number=\"50\">0</strong> <span>Years\n");
      out.write("\t\t\t\t\t\t\t\t\t\tof Experienced</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-md-6 d-flex justify-content-center counter-wrap ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-18\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"number\" data-number=\"4500\">0</strong> <span>Customers\n");
      out.write("\t\t\t\t\t\t\t\t\t\tServed</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-md-6 d-flex justify-content-center counter-wrap ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-18\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"number\" data-number=\"300\">0</strong> <span>Number\n");
      out.write("\t\t\t\t\t\t\t\t\t\tof Equipment</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-md-6 d-flex justify-content-center counter-wrap ftco-animate\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-18\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong class=\"number\" data-number=\"300\">0</strong> <span>Number\n");
      out.write("\t\t\t\t\t\t\t\t\t\tof Staffs</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section class=\"ftco-intro img\"\n");
      out.write("\t\tstyle=\"background-image: url(/resources/images/bg_3.jpg);\">\n");
      out.write("\t\t<div class=\"overlay\"></div>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\n");
      out.write("\t\t\t\t<div class=\"col-md-12 text-center\">\n");
      out.write("\t\t\t\t\t<h2>We Are Equipo A Heavy Equipment Renting Company</h2>\n");
      out.write("\t\t\t\t\t<p>We can manage your dream building A small river named Duden\n");
      out.write("\t\t\t\t\t\tflows by their place</p>\n");
      out.write("\t\t\t\t\t<p class=\"mb-0\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary px-4 py-3\">Make An\n");
      out.write("\t\t\t\t\t\t\tAppointment</a>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section class=\"ftco-section\">\n");
      out.write("\t\t<div class=\"container-fluid px-md-4\">\n");
      out.write("\t\t\t<div class=\"row justify-content-center mb-5 pb-2\">\n");
      out.write("\t\t\t\t<div class=\"col-md-8 text-center heading-section ftco-animate\">\n");
      out.write("\t\t\t\t\t<span class=\"subheading\">Services</span>\n");
      out.write("\t\t\t\t\t<h2 class=\"mb-4\">Rental Services</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t<div class=\"services-wrap\">\n");
      out.write("\t\t\t\t\t\t<div class=\"img\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/services-1.jpg);\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t<h2>Bulldozer</h2>\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\t\t\tcountries Vokalia and Consonantia</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t<div class=\"services-wrap\">\n");
      out.write("\t\t\t\t\t\t<div class=\"img\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/services-2.jpg);\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t<h2>Forklift</h2>\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\t\t\tcountries Vokalia and Consonantia</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t<div class=\"services-wrap\">\n");
      out.write("\t\t\t\t\t\t<div class=\"img\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/services-3.jpg);\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t<h2>Crane</h2>\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\t\t\tcountries Vokalia and Consonantia</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t<div class=\"services-wrap\">\n");
      out.write("\t\t\t\t\t\t<div class=\"img\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/services-4.jpg);\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t<h2>Excavator</h2>\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\t\t\tcountries Vokalia and Consonantia</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section class=\"ftco-section testimony-section img\"\n");
      out.write("\t\tstyle=\"background-image: url(/resources/images/bg_1.jpg);\">\n");
      out.write("\t\t<div class=\"overlay\"></div>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row justify-content-center mb-5 pb-3\">\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"col-md-7 text-center heading-section heading-section-white ftco-animate\">\n");
      out.write("\t\t\t\t\t<span class=\"subheading\">Read Testimonials</span>\n");
      out.write("\t\t\t\t\t<h2 class=\"mb-4\">Our Happy Customer Says</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row ftco-animate justify-content-center\">\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t<div class=\"carousel-testimony owl-carousel ftco-owl\">\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/person_1.jpg)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"quote d-flex align-items-center justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfar from the countries Vokalia</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/person_2.jpg)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"quote d-flex align-items-center justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfar from the countries Vokalia</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/person_3.jpg)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"quote d-flex align-items-center justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfar from the countries Vokalia</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/person_1.jpg)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"quote d-flex align-items-center justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfar from the countries Vokalia</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"testimony-wrap py-4 pb-5 d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user-img\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"background-image: url(/resources/images/person_3.jpg)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"quote d-flex align-items-center justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-4\">Far far away, behind the word mountains,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfar from the countries Vokalia</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"name\">Jeff Freshman</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"position\">Guests</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<section class=\"ftco-section bg-light\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row justify-content-center mb-5 pb-3\">\n");
      out.write("\t\t\t\t<div class=\"col-md-10 heading-section text-center ftco-animate\">\n");
      out.write("\t\t\t\t\t<span class=\"subheading\">Our Blog</span>\n");
      out.write("\t\t\t\t\t<h2 class=\"mb-4\">Latest Blog Updates</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row d-flex\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 ftco-animate\">\n");
      out.write("\t\t\t\t\t<div class=\"blog-entry\">\n");
      out.write("\t\t\t\t\t\t<a href=\"blog-single.html\" class=\"block-20\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url('/resources/images/image_1.jpg');\"> </a>\n");
      out.write("\t\t\t\t\t\t<div class=\"text d-block\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-calendar mr-2\"></span>Aug.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t27, 2020</a> <a href=\"#\"><span class=\"fa fa-user mr-2\"></span>Admin</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"meta-chat\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-comment mr-2\"></span> 3</a>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"heading\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">New Heavy Equipment To Launch</a>\n");
      out.write("\t\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\t\t\tcountries Vokalia and Consonantia...</p>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"blog.html\" class=\"btn btn-secondary py-2 px-3\">Read\n");
      out.write("\t\t\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 ftco-animate\">\n");
      out.write("\t\t\t\t\t<div class=\"blog-entry\">\n");
      out.write("\t\t\t\t\t\t<a href=\"blog-single.html\" class=\"block-20\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url('/resources/images/image_2.jpg');\"> </a>\n");
      out.write("\t\t\t\t\t\t<div class=\"text d-block\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-calendar mr-2\"></span>Aug.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t27, 2020</a> <a href=\"#\"><span class=\"fa fa-user mr-2\"></span>Admin</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"meta-chat\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-comment mr-2\"></span> 3</a>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"heading\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">New Heavy Equipment To Launch</a>\n");
      out.write("\t\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\t\t\tcountries Vokalia and Consonantia...</p>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"blog.html\" class=\"btn btn-secondary py-2 px-3\">Read\n");
      out.write("\t\t\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 ftco-animate\">\n");
      out.write("\t\t\t\t\t<div class=\"blog-entry\">\n");
      out.write("\t\t\t\t\t\t<a href=\"blog-single.html\" class=\"block-20\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url('/resources/images/image_3.jpg');\"> </a>\n");
      out.write("\t\t\t\t\t\t<div class=\"text d-block\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-calendar mr-2\"></span>Aug.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t27, 2020</a> <a href=\"#\"><span class=\"fa fa-user mr-2\"></span>Admin</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"meta-chat\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-comment mr-2\"></span> 3</a>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"heading\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">New Heavy Equipment To Launch</a>\n");
      out.write("\t\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\t\t\tcountries Vokalia and Consonantia...</p>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"blog.html\" class=\"btn btn-secondary py-2 px-3\">Read\n");
      out.write("\t\t\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<footer class=\"ftco-footer\">\n");
      out.write("\t\t<div class=\"container mb-5 pb-4\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg col-md-6\">\n");
      out.write("\t\t\t\t\t<div class=\"ftco-footer-widget\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"ftco-heading-2 logo d-flex align-items-center\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><span class=\"flaticon-road-roller flaticon\"></span><span>Equipo</span></a>\n");
      out.write("\t\t\t\t\t\t</h2>\n");
      out.write("\t\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\n");
      out.write("\t\t\t\t\t\t\tcountries.</p>\n");
      out.write("\t\t\t\t\t\t<ul class=\"ftco-footer-social list-unstyled mt-4\">\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-twitter\"></span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-facebook\"></span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-instagram\"></span></a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-lg col-md-6\">\n");
      out.write("\t\t\t\t\t<div class=\"ftco-footer-widget\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"ftco-heading-2\">Links</h2>\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-unstyled\">\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>About\n");
      out.write("\t\t\t\t\t\t\t\t\tUs</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Rental\n");
      out.write("\t\t\t\t\t\t\t\t\tServices</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Blog</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Contact</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-lg col-md-6\">\n");
      out.write("\t\t\t\t\t<div class=\"ftco-footer-widget\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"ftco-heading-2\">Services</h2>\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-unstyled\">\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Customer\n");
      out.write("\t\t\t\t\t\t\t\t\tServices</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Prompt\n");
      out.write("\t\t\t\t\t\t\t\t\tDelivery</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>Reliable\n");
      out.write("\t\t\t\t\t\t\t\t\tEquipment</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-chevron-right mr-2\"></span>New\n");
      out.write("\t\t\t\t\t\t\t\t\tHeavy Equipment</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-lg col-md-6\">\n");
      out.write("\t\t\t\t\t<div class=\"ftco-footer-widget\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"block-23 mb-3\">\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><span class=\"fa fa-map-marker mr-3\"></span><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"text\">203 Fake St. Mountain View, San Francisco,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tCalifornia, USA</span></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-phone mr-3\"></span><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"text\">+2 392 3929 210</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"fa fa-paper-plane mr-3\"></span><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"text\">info@yourdomain.com</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"container-fluid bg-primary py-5\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-12 text-center\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<p class=\"mb-0\">\n");
      out.write("\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("\t\t\t\t\t\tCopyright &copy;\n");
      out.write("\t\t\t\t\t\t<script>\n");
      out.write("\t\t\t\t\t\t\tdocument.write(new Date().getFullYear());\n");
      out.write("\t\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t\tAll rights reserved | This template is made with <i\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a\n");
      out.write("\t\t\t\t\t\t\thref=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- loader -->\n");
      out.write("\t<div id=\"ftco-loader\" class=\"show fullscreen\">\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\">\n");
      out.write("\t\t\t<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke=\"#eeeeee\" />\n");
      out.write("\t\t\t<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script src=\"/resources/js/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/jquery-migrate-3.0.1.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/popper.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/jquery.easing.1.3.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/jquery.waypoints.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/jquery.stellar.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/owl.carousel.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/jquery.animateNumber.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/bootstrap-datepicker.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/jquery.timepicker.min.js\"></script>\n");
      out.write("\t<script src=\"/resources/js/scrollax.min.js\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\n");
      out.write("\t<script src=\"/resources/js/google-map.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"/resources/js/main.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
